Quotes fetching
BenM4k/math_magician_ pull request #4
Opened 2023-05-30 10:15 UTC by BenM4k

In this update, I: 
- Used the following external API: [API Ninjas](https://api-ninjas.com/api/quotes) to fetch quotes
- Created a new component for displaying a quote
- Show a loading state
- Show an error state
- Imported the new component into my main component (next to the Calculator)

2023-05-30 10:46 UTC, Mihndim2020 requested changes
### Hi @BenM4k, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark:  Clean and Organized code
:heavy_check_mark: Descriptive Readme file

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)

# Status: Requires Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

#### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 10:46 UTC, Mihndim2020 commented on src/components/Quotes.js
> +  const [isPending, setIsPending] = useState(true);
- [ ] As it is a [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_fetch_data_from_api.md) of this project,  "`Show an error state`", please make sure errors are handled it there are any, during search. Something like so: 

``` 
const [hasError, setHasError] = useState(false)
```
The `hasError` variable should be set to `true` in case of an error. You can use `try...catch` to catch any errors and set `hasError` variable, checkout this [article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) for MDN.

2023-05-30 11:12 UTC, prolajumokeoni approved these changes
Hi @BenM4k 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - All changes requested have been implemented 🥇  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 11:14 UTC, merged

2023-07-03 12:36 UTC, omarsalem7 commented
Hi @BenM4k 😊, 
# STATUS: APPROVED! 🥇 💯 

<!--- ![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif) -->

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._